services:
  agent-zero:
    container_name: agent-zero
    build: 
      context: .
      dockerfile: Dockerfile
      # This 'args' section passes the BRANCH variable into the build process.
      args:
        - BRANCH=main
    image: my-agent-zero
    volumes:
      - ../../:/a0
    ports:
      - "50080:80"